version: '2'

services:
  bind:
    image: vukomir/bind
    container_name: bind.app
    hostname: bind
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./bindconfig:/etc/bind
      - ./logs:/var/log/named
